### ISSUE TITLE
Libtorrent is not found

### ISSUE THREAD

**Issue by kertmannik** [Jalle19/libreelec-docker-deluge#20]
Hey! I have Libreelec 10.0.2 running on Pi3 and I would like to use Deluge. I am following your instructions and I have an error when I an building the Docker image. 

Collecting pip
  Downloading pip-22.1.2-py3-none-any.whl (2.1 MB)
Installing collected packages: pip
  Attempting uninstall: pip
    Found existing installation: pip 20.0.2
    Not uninstalling pip at /usr/lib/python3/dist-packages, outside environment /usr
    Can't uninstall 'pip'. No files were found to uninstall.
Successfully installed pip-22.1.2
Collecting rjsmin
  Downloading rjsmin-1.2.0.tar.gz (419 kB)
Building wheels for collected packages: rjsmin
  Building wheel for rjsmin (setup.py): started
  Building wheel for rjsmin (setup.py): finished with status 'done'
  Created wheel for rjsmin: filename=rjsmin-1.2.0-cp38-cp38-linux_armv7l.whl size=44537 sha256=102221c6ba776c49cf88cf3e7e6d1a3083c71800556cb9db57ce0d8c33d09b43
  Stored in directory: /root/.cache/pip/wheels/2e/f8/c1/128dad44a24236827b66b3f51cb1321da71ce3f9e5cffbf3ea
Successfully built rjsmin
Installing collected packages: rjsmin
Successfully installed rjsmin-1.2.0
ERROR: Could not find a version that satisfies the requirement libtorrent==1.2.15 (from versions: none)
ERROR: No matching distribution found for libtorrent==1.2.15

Seems like it that it can not find libtorrent, but when I checked pypi.org website, it is present.
Do you have any ideas what to do?

**Comment by Jalle19** [comment]
Interesting, it seems the current build only works on x86. I'll have to test it on ARM as well in order to come up with a solution.
