### ISSUE TITLE
Support ARM too

### ISSUE THREAD

**Issue by Jalle19** [Jalle19/libreelec-docker-deluge#3]
This needs some code reshuffling and some modifications to the build script. The code that inspired this project used different directory trees for different architectures because it compiled things in Dockerfile, something this one doesn't do, so it should be possible to combine everything nicely.

Need to get some ARM hardware first though...

**Comment by epopcop** [comment]
I have a raspberry pi 3b
If you want.. I will test for you.

**Comment by Jalle19** [comment]
I have a bunch too that more or less should work, I just need to buy SD cards. if you want to experiment, feel free to submit a pull request.
