### ISSUE TITLE
Torrent gone after reboot

### ISSUE THREAD

**Issue by patricklibert** [Jalle19/libreelec-docker-deluge#4]
Hi,

Just trying deluge for libreelec for the first time.
Everything is working but when I reboot the torrent is gone in deluge. The data is still there on /var/media/xxx

Is it possible to fix?

**Comment by patricklibert** [comment]
In the directory /storage/deluge/config there is a file named "state". This is wrong. It should be a directory named "state".

Everything is working now.

**Comment by Jalle19** [comment]
Are you sure it's supposed to be a directory?

**Comment by patricklibert** [comment]
Of course, thats where the hashes of the torrent are stored.

Look at my terminal output.






LibreELEC (official): 8.2.4 (Generic.x86_64)
LibreELEC:~ # cd /storage/deluge/config/state
LibreELEC:~/deluge/config/state # ls
64d58b9a199dd7c0cee71db13a14e7b0ce054144.torrent
8f685014c14b7450712b128d5e6fedffe570823b.torrent
torrents.fastresume
torrents.fastresume.bak
torrents.state
torrents.state.bak
LibreELEC:~/deluge/config/state #

**Comment by Jalle19** [comment]
It looks like you're right, no idea what I was thinking when I added a file there. I'll come up with a fix.
